#!/bin/ksh

# this script should be run only one time.
# If any of the configurations are in place, the script should end
# it is supposed to be idempotent so if it's run again, it should just
# exit with, 'already in place'

if [[ -z ${1} ]]
then
  echo "Error: Missing the service name"
  ls -l
  exit 1
fi

HERE=$(pwd)
SERVICE=${1}

for i in $(find ${SERVICE}  -type d -print)
do
  cd ${i}

  if [[ -f main.tf ]]
  then
    terraform init
    terraform plan
    terraform apply -auto-approve
  fi

  cd ${HERE}

done

