#!/bin/ksh

echo "terraform {"
echo "  required_providers {"
echo "    libvirt = {"
echo "      source  = \"dmacvicar/libvirt\""
echo "      version = \"0.6.11\""
echo "    }"
echo "  }"
echo "}"
echo ""

for i in `grep nikodemus server.data`
do
  NUMBER=$(       echo $i | cut -f1 -d,)
  MACHINE_NAME=$( echo $i | cut -f6 -d,)
  MAC_ADDRESS=$(  echo $i | cut -f7 -d,)
  IP_ADDRESS=$(   echo $i | cut -f8 -d,)
  MACHINE_IMAGE=$(echo $i | cut -f9 -d,)
  RAM_REQUEST=$(  echo $i | cut -f10 -d,)
  CPU_REQUEST=$(  echo $i | cut -f11 -d,)

  echo "module \"SITENAME-server-${NUMBER}\" {"
  echo "# load the module"
  echo "  source = \"../../../../modules/single/\""
  echo ""
  echo "# set the variables"
  echo "  machine_name = \"${MACHINE_NAME}\""
  echo "  svc_bridge = \"br0\""
  echo "  svc_address = \"${IP_ADDRESS}\""
  echo "  mac_address = \"${MAC_ADDRESS}\""
  echo "  ram_request = \"${RAM_REQUEST}\""
  echo "  cpu_request = \"${CPU_REQUEST}\""
  echo "  machine_image = \"${MACHINE_IMAGE}\""
  echo "  user_data_path = \"\${path.module}/${MACHINE_NAME}.yaml\""
  echo "}"
  echo ""

done

